import manifest from "@/data/image-manifest.json";
import type { ImageRef } from "@/data/types";

type ManifestEntry = {
  widths: number[];
  width: number;
  height: number;
  aspectRatio: number;
};

const images = manifest as Record<string, ManifestEntry>;

/**
 * Renders a manifest-backed responsive <img> with explicit dimensions (no CLS).
 * Variants are pre-generated by scripts/optimize-images.mjs.
 */
export default function Picture({
  image,
  sizes = "(max-width: 768px) 100vw, 50vw",
  className = "",
  priority = false,
}: {
  image: ImageRef;
  sizes?: string;
  className?: string;
  priority?: boolean;
}) {
  const entry = images[image.src];
  if (!entry) {
    throw new Error(`Image "${image.src}" missing from image-manifest.json`);
  }
  const srcSet = entry.widths
    .map((w) => `/images/${image.src}-${w}.webp ${w}w`)
    .join(", ");
  const largest = entry.widths[entry.widths.length - 1];

  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={`/images/${image.src}-${largest}.webp`}
      srcSet={srcSet}
      sizes={sizes}
      alt={image.alt}
      width={entry.width}
      height={entry.height}
      loading={priority ? "eager" : "lazy"}
      decoding="async"
      className={className}
    />
  );
}
